### ISSUE TITLE
UNMS 1.0.5 - Raspberry Pi 3 B+ hangs after some minutes 

### ISSUE THREAD

**Issue by pr3mi3r3** [Nico640/docker-unms#11]
After a fresh docker-compose installation the raspberry Pi 3 B+ hangs after some minutes, I have to power restart the raspberry pi. 

Here is my docker-compose file:

version: '2'
services:
  unms:
    image: nico640/docker-unms:armhf  # use "armhf" instead of "latest" for arm devices
    restart: always
    ports:
      - 80:80
      - 443:443
      - 2055:2055/udp
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./volumes/unms:/config

**Comment by Nico640** [comment]
Hi,
I have also noticed this, however, the fact that this didn't happen to me yet with a Pi4 makes me think that this is caused by the limited resources the Pi3B+ has. I'll try do to some more testing, but my guess is that the Pi3B+ can't really handle both UNMS and UCRM doing their first-time initialization.

**Comment by pr3mi3r3** [comment]
Thanks for the reply.
If the limited resources are the real reason, it would be nice if you could release a version without UCRM as before. For supporting older raspberry devices.
In the meantime, how can I pull the older working version 0.14.4 with my docker-compose file?

**Comment by Nico640** [comment]
Hi,

I don't think UNMS v1.X.X without UCRM will be possible. UNMS v1 does have UCRM far more integrated than 0.14.X has. Even the 0.14.X versions had problems without UCRM (e.g. automatic backups).
The old 0.14.X images are no longer on docker hub, because they only were pre-releases. If you really need the 0.14.X images, you can always build them from source by selecting the corresponding tag.

**Comment by Nico640** [comment]
Small update,
I did multiple fresh installs on Raspbian Desktop as well as on Raspbian Lite.
I could only reproduce these freezes on Raspbian Desktop, they only were a few seconds long and didn't really interfere with the installation. On both Raspbian versions the Pi did slow down while setting up UNMS and UCRM for the first time, but even though the installation wasn't as smooth as on a Pi 4, UNMS and UCRM ran fine after the installation.

So if there isn't a lot of other stuff running on the Pi, UNMS and UCRM are still very usable on the 3B+, but I would definitely choose Raspbian Lite to save some resources.

**Comment by pr3mi3r3** [comment]
Yes that is true. Only UNMS is working good, but I want to use the UniFi controller on the same Pi. This is too much for the 3B+. You can close this issue...
