### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by azim254** [Nico640/docker-unms#26]
are you guys maintaining this repo from oznu

**Comment by Nico640** [comment]
Yes. I am maintaining this fork and currently updating it to 1.1.7

**Comment by azim254** [comment]
nice 😀

**Comment by azim254** [comment]
could you create a new repository so that i can fork it since the maintainer of the main repository isnt maintaining it

**Comment by Nico640** [comment]
You should be able to fork it, some have already done it
https://github.com/Nico640/docker-unms/network/members

**Comment by Danabw** [comment]
Re: 
- "You can upgrade UNMS by downloading the latest version of this image."

Is it possible to provide Docker noob upgrade instructions? I've been Googling around but don't find a consistent answer (maybe because there are multiple ways?) to upgrade to the new release. I'm a bit confused.

Is it as simple removing the current unms container and repeating the command below that I used the first time I installed? 

`sudo docker run -d --name unms -p 80:80 -p 443:443 -p 2055:2055/udp -v /var/lib/docker-config/unms:/config nico640/docker-unms:armhf`

**Comment by azim254** [comment]
thanks 😊

**Comment by Nico640** [comment]
Question resolved
