### ISSUE TITLE
no unms-cli included

### ISSUE THREAD

**Issue by RCFilm** [Nico640/docker-unms#4]
since no unms-cli is included we are unable to set super-user

**Comment by Nico640** [comment]
I'll look into including unms-cli, however, unms-cli would probably need a few changes because it uses docker-compose to interact with the individual containers from the host system, but this all-in-one image only uses one container.

In the meantime you can launch an bash shell on the container, navigate to /home/app/unms and execute "node setpwd.js superadmin USER" to set a user as superadmin.

**Comment by RCFilm** [comment]
i see, Thank you
I was looking in the ~/unms for the .js

**Comment by philipp65** [comment]
inside the container (`docker exec -it unms bash`)
```
cd /home/app/unms/cli
node user.js superadmin USER
```
