### ISSUE TITLE
container behind cloudflare tunnel

### ISSUE THREAD

**Issue by LucaMH** [Nico640/docker-unms#78]
Hi,
first of all, amazing project, really makes it easy to selfhost without the 5+ container setup UI provides.

Has anyone tried to make it publicly accessible via a cloudflare tunnel?
For me it looks like it fails because the container has a certificate for "localhost" which does not work when cloudflare puts the certificate in via the tunnel.
```
2022-11-06T20:10:43Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: x509: cannot validate certificate for 172.16.42.29 because it doesn't contain any IP SANs" cfRay=xxxxxxxx-AMS ingressRule=4 originService=https://172.16.42.29:28117
2022-11-06T20:10:43Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: x509: cannot validate certificate for 172.16.42.29 because it doesn't contain any IP SANs" connIndex=0 dest=https://uisp.yyyy.zzzzz/ ip=198.41.200.233 type=http
```

So basically the solution would be to be able to access the container via http (without https redirect) locally.
Is that possible?

Thanks!

**Comment by sinegar** [comment]
After the readme ( https://github.com/Nico640/docker-unms#parameters ), you can expose http port by adding `-p 80:80`. 

Otherwise, you can disable TLS verification in cloudflare: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/ingress/#notlsverify

Third, you can run uisp behind a reverse proxy like traefik that can manage certs for you.

**Comment by Nico640** [comment]
Hi, sorry for the late reply, but in addition to the ways sinegar already provided, another way would be to generate a Origin Certificate at Cloudflare and use that for the container via the `SSL_CERT` and `SSL_CERT_KEY` environment variables. I personally use the third option that sinegar provided and run UISP behind Traefik. The traefik port is then used for the cloudflared tunnel.
Accessing UISP only via http is not supported because as far as I know, UISP itself doesn't support that either because they use wss (WebSocket over HTTPS) for connecting to the devices.

**Comment by LucaMH** [comment]
Sorry for the even later reply....

Indeed, enabling "No TLS Verify" for in the Public Hostname Page in the Cloudflare tunnel did the trick.
Never thought about going through the options there. Thx for the tip @sinegar !

![image](https://user-images.githubusercontent.com/22506082/209400747-6b3444f1-7a19-47d5-a35f-b846b0b6e141.png)
