### ISSUE TITLE
How to get UNMS (UISP) to take a lets encrypt (or converted) .key/.crt using docker-compose, no Wiki info.

### ISSUE THREAD

**Issue by GuruSR** [Nico640/docker-unms#83]
Using docker-compose.yml, has anyone gotten a script working from letsencrypt that'll give a proper .key and .crt file that I can aim (somehow, couldn't find any docs) unms at?

**Comment by Nico640** [comment]
Hi,

one way to archieve this would be to use the built-in Let's Encrypt functionality of UISP. For that you would need to enter your domain name in the UISP settings (UISP Hostname/IP) and turn on "Use Let's Encrypt" under the SSL Certificate settings. UISP has to be reachable with that domain name with both http and https.

Another way would be to create the Let's Encrypt certificate outside of the container (for example with certbot, acme.sh) and then pass the certificate to the container using the SSL_CERT and SSL_CERT_KEY environment variables, as listed in the readme.

**Comment by GuruSR** [comment]
Have you seen any good cron script that offers the ability to copy, chmod/chown and restart the container so that the certificate can be updated?  I'm trying to track one down that'll offer this ability, as I do do Let's Encrypt outside the container for the whole system and need a method to get this and others up to date.

**Comment by Nico640** [comment]
Do you need a cron script for that? What are you using to create the Let's Encrypt certificates outside the container? If you use something like certbot or acme.sh, then you should be able to use the `--post-hook` flag to execute a script that simply copies the certificate and restarts the container after the certificate has been renewed.

**Comment by GuruSR** [comment]
I am noticing at 4AM each day the following is modified in the cert folder:
`lrwxrwxrwx  1 nutjob 65533   15 Apr 23 04:00 live.crt -> ./localhost.crt
lrwxrwxrwx  1 nutjob 65533   15 Apr 23 04:00 live.key -> ./localhost.key
`
Lets Encrypt is OFF in the server, though I did change the server site from the IP address to the domain name and now it is showing the proper cert since I manually copied them to the localhost.crt/.key, this 4AM schedule, no clue where that is in the settings, will this re-read the certificates at 4AM?  If so, this lessens my job to get the certs updated, as UISP is now showing the proper ones.

**Comment by Nico640** [comment]
Yes, it looks like `/refresh-configuration.sh` is executed daily. It checks if the certificate is about to expire, if it is, it creates a new one (if not using SSL_CERT/KEY environment variables). Even if it isn't about to expire, it will always re-create the soft links and reload the nginx configuration, which will also re-read the certificates. By the way, you should also be able to trigger this from the host system by executing something like

`docker exec CONTAINER_NAME /refresh-certificate.sh --self-signed HOSTNAME` (if not using SSL_CERT/KEY environment variables)
or 
`docker exec CONTAINER_NAME /refresh-certificate.sh --custom HOSTNAME` (if using SSL_CERT/KEY environment variables)
where `CONTAINER_NAME` is the docker container name and `HOSTNAME` is the hostname configured in UISP.

Also, you said that you manually overwrote the localhost.crt/.key, which isn't really recommended because they could get overwritten by UISP again. That's exactly what the SSL_CERT and SSL_CERT_KEY environment variables are for. You simply place your certificates in the /config/usercert directory instead of /config/cert, for example domain.crt and domain.key. Then you set SSL_CERT to domain.crt and SSL_CERT_KEY to domain.key. This will tell UISP that you are using your own certificates and it shouldn't try to generate any.

**Comment by GuruSR** [comment]
> Yes, it looks like `/refresh-certificate.sh` is executed daily. It checks if the certificate is about to expire, if it is, it creates a new one (if not using SSL_CERT/KEY environment variables). 

I have LetsEncrypt off, should that run at all?

> `docker exec CONTAINER_NAME /refresh-certificate.sh --custom HOSTNAME` (if using SSL_CERT/KEY environment variables) where `CONTAINER_NAME` is the docker container name and `HOSTNAME` is the hostname configured in UISP.

I'll try that next time the certificates come up for updating, after I get a script working with LetsEncrypt, I'll have to wait and see how that works (or not), unsure since the certbot apparently might not work with it.

I've added the variables to the docker-compose.yml, guess it'll only be a "test to see if it works" situation.  Anything I should look for in the log to make sure there is no issues?

**Comment by GuruSR** [comment]
The private cert keys updated (after I ran the script [7 days after certbot quietly updated them on me]), so that means this is good.  :)  Thanks for the assistance.
