### ISSUE TITLE
Docker Compose Version

### ISSUE THREAD

**Issue by bryanembley** [Nico640/docker-unms#95]
I'm running UISP on Ubuntu 20.04.6 and the update script has produced the following for the last two updates:

`bryan@uispserver:~$ curl -fsSL https://uisp.ui.com/v1/install > /tmp/uisp_inst.sh && sudo bash /tmp/uisp_inst.sh --update
branch=master
version=2.3.35
Downloading installation package for version 2.3.35.
Restoring previous configuration
Error: No such object: unms
Couldn't read WS port config from existing UISP container
Reading configuration file /home/unms/app/unms.conf
Setting VERSION=2.3.35
Distribution: 'ubuntu 20.04'
Docker version: 20.10.24
Docker compose version: Docker Compose version v2.17.2
Docker compose version Docker Compose version v2.17.2 is not supported. Would you like to update docker compose automatically? [Y/N]Y
Yes
snap "docker" has no updates available
ERROR: Docker compose version Docker Compose version v2.17.2 is not supported. Please upgrade to version 1.24.1 or newer.`

I understand that the docker version is actually newer on the system but I can't figure out how to either step down the docker version or get the install script to move forward. Any help would be appreciated.

**Comment by Nico640** [comment]
Sorry for the late response, it looks like you're using the official UISP install script rather than this repository's 3rd party docker container.

I did find this post with the same issue suggesting that removing the docker snap package fixes the issue: https://community.ui.com/releases/UISP-Application-2-3-39/fb6074ef-06ae-4a7c-afe4-a79d61ff5bb0#comment/0b613160-0e06-4c08-a7b0-ca899f103fe5

But this repository is meant for a 3rd party container, so I would suggest you to contact Ubiquiti support or create a post on their community forum if this is still a problem.
